version: '3.7'
services:
  app:
    image: mhrznamn068/callalert:latest
    container_name: callalert
    ports:
      - 5000:5000
    env_file:
      - ./.env
    volumes:
      - ${LOCAL_KEY_PATH}:/root/.ssh/id_rsa_zabbix:ro

  nginx:
    image: nginx
    ports:
      - 5080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d

