version: '3.7'
services:
  app:
    build: .
    image: callalert-django
    ports:
      - 4000:4000
    env_file:
      - ./.env
    volumes:
      - ./djangoapp:/app
      - ${LOCAL_KEY_PATH}:/app/.ssh/id_rsa