version: '3.7'
services:
  app:
    build: .
    image: callalert
    container_name: callalert
    ports:
      - 5000:5000
    env_file:
      - ./.env
    volumes:
      - asterisk_data:/var/lib/asterisk"
      - asterisk_spool:/var/spool/asterisk
  
  asterisk:
    build: ./asterisk
    image: asterisk:18
    container_name: asterisk
    volumes:
      - asterisk_config:/etc/asterisk"
      - asterisk_data:/var/lib/asterisk"
      - asterisk_spool:/var/spool/asterisk"
    ports:
      - 5060:5060/udp
      - 5060:5060/tcp
      - 5065:5065/udp
      - 5065:5065/tcp
      - 10000-10099:10000-10099/udp
      - 8088:8088
      - 8089:8089

volumes:
  asterisk_config:
    name: asterisk_config
  asterisk_data:
    name: asterisk_data
  asterisk_spool:
    name: asterisk_spool