# Generated by Django 4.1.6 on 2023-02-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alerthistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_date', models.DateTimeField(verbose_name='date alert generated')),
                ('alert_text', models.CharField(max_length=1000)),
                ('alert_recording', models.CharField(max_length=200)),
                ('alert_receviers', models.CharField(max_length=200)),
            ],
        ),
    ]
