# Generated by Django 4.1.6 on 2024-01-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callalert', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerthistory',
            name='alert_date',
        ),
        migrations.RemoveField(
            model_name='alerthistory',
            name='alert_receviers',
        ),
        migrations.RemoveField(
            model_name='alerthistory',
            name='alert_recording',
        ),
        migrations.RemoveField(
            model_name='alerthistory',
            name='alert_text',
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='destination_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='trigger_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='trigger_severity',
            field=models.CharField(default='', max_length=255),
        ),
    ]
