# Generated by Django 4.1.6 on 2024-01-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callalert', '0003_shift_alerthistory_details_alerthistory_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerthistory',
            name='call_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
