# Generated by Django 4.1.6 on 2024-01-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callalert', '0006_userprofile_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerthistory',
            name='destination_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
