# Generated by Django 4.1.6 on 2024-01-14 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('callalert', '0007_alter_alerthistory_destination_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oncallduty',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='oncallduty',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='oncallduty',
            name='start_time',
        ),
        migrations.AddField(
            model_name='oncallduty',
            name='duty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='oncallduty',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
